### ISSUE TITLE
Register Users

### ISSUE THREAD

**Issue by jannypie** [fifthbymidwest/fifthbymidwest.github.io#11]
*As a user I want to register so that I can use the site.*

#### Functional

Note: strike outs indicate pieces that are being broken out into their own, smaller, user stories.

- User can register with the site using their information.
- Users should be able to register with the following *required* information
  - Full name (first and last)
  - Email (unique per account)
~~- Birthdate~~
~~- Home address~~
- Users should be able to register with the following *optional* information
~~- Phone~~
- User should set a password for security
~~- User should be able to reset password~~
- User should be able to edit their personal information
- Registered Users should be able to Log In if not
- Logged In users should be able to Log Out
~~- User pages should only be viewable to the user~~ 

#### Operational

- User should have a dedicated page to view and edit their information
~~- User should have a dedicated page to reset their password~~
- Home page should have a form (or link to one) for users to use to register 
- Home page should have a form (or link to one) for users to use to log in
- Home page should have a link for users to use to sign out

**Comment by rebootunity** [comment]
Breaking this story up into smaller pieces
#21 
#20

**Comment by rebootunity** [comment]
User story completed with PR #18
